# Generated by Django 5.1.4 on 2025-01-06 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises_proprietaire', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprise_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='fact_gest.company')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoye', 'Envoye'), ('Paye', 'Paye'), ('En attente', 'En attente'), ('Annule', 'Annuler')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fact_gest.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fact_gest.company')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creee', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'groupe',
                'verbose_name_plural': 'groupes',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='fact_gest.group'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='fact_gest.company')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
            },
        ),
        migrations.CreateModel(
            name='FactureProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_factures', to='fact_gest.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fact_gest.produit')),
            ],
            options={
                'verbose_name': 'facture produit',
                'verbose_name_plural': 'factures produits',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fact_gest.company')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='FactureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_factures', to='fact_gest.facture')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fact_gest.service')),
            ],
            options={
                'verbose_name': 'facture service',
                'verbose_name_plural': 'factures services',
            },
        ),
    ]
