# Generated by Django 5.1.4 on 2025-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_gest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
