# Generated by Django 5.1.4 on 2025-01-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_gest', '0002_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CahierDeCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='cahiers_de_charges/')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='tarif',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='cahier_de_charges',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fact_gest.cahierdecharges'),
            preserve_default=False,
        ),
    ]
