# Generated by Django 5.1.4 on 2025-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_gest', '0003_cahierdecharges_alter_service_tarif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoye', 'Envoye'), ('Paye', 'Paye'), ('En attente', 'En attente'), ('Avance', 'Avance'), ('Annule', 'Annuler')], max_length=20),
        ),
    ]
